import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.widgets import Button, Slider

start = pd.read_csv("initial.dat", sep=" ")
solution = pd.read_csv("analitycal.dat", sep=" ")
c06 = pd.read_csv("c06.dat", sep=" ")
c09 = pd.read_csv("c09.dat", sep=" ")
c10 = pd.read_csv("c10.dat", sep=" ")
n32 = pd.read_csv("n32.dat", sep=" ")
n64 = pd.read_csv("n64.dat", sep=" ")
n128 = pd.read_csv("n128.dat", sep=" ")

t000 = pd.read_csv("t000.dat", sep=" ")
t025 = pd.read_csv("t025.dat", sep=" ")
t050 = pd.read_csv("t050.dat", sep=" ")
t075 = pd.read_csv("t075.dat", sep=" ")
t100 = pd.read_csv("t100.dat", sep=" ")

plt.title("n = 32")
plt.plot(start["t"], start["x"], label="Initial")
plt.plot(solution["t"], solution["x"], label="Exact solution")
plt.plot(c06["t"], c06["x"], label="c = 0.6")
plt.plot(c09["t"], c09["x"], label="c = 0.9")
plt.plot(c10["t"], c10["x"], label="c = 1.0")
plt.xlabel("X")
plt.ylabel("U")
plt.legend()
plt.show()

plt.title("c = 0.9")
plt.plot(start["t"], start["x"], label="Initial")
plt.plot(solution["t"], solution["x"], label="Exact solution")
plt.plot(n32["t"], n32["x"], label="n = 32")
plt.plot(n64["t"], n64["x"], label="n = 64")
plt.plot(n128["t"], n128["x"], label="n = 128")
plt.xlabel("X")
plt.ylabel("U")
plt.legend()
plt.show()

plt.title("n = 1024, c = 0.99")
plt.plot(t000["t"], t000["x"], label="t = 0.00")
plt.plot(t025["t"], t025["x"], label="t = 0.25")
plt.plot(t050["t"], t050["x"], label="t = 0.50")
plt.plot(t075["t"], t075["x"], label="t = 0.75")
plt.plot(t100["t"], t100["x"], label="t = 1.00")
plt.xlabel("X")
plt.ylabel("U")
plt.legend()
plt.show()
